### PR TITLE
Add by_magic check for CSV files.

### PR DESCRIPTION
**Pull request by seabre**
Adds a memory efficient way to test to see if a file is probably a CSV file or not. Hooks into the magic_matching functionality.

### CODE REVIEW

**Comment by minad** [comment]
I won't merge any special checks for special filetypes. Either fix the upstream magic database or add a patch to the overlay.

**Comment by seabre** [comment]
Can you give some direction on how to possibly do that with a CSV using the overlay? There really isn't a way to check if a file is a CSV or not without checking at least part of its structure. There doesn't seem to be a way to do that as-is.

**Comment by minad** [comment]
This is probably true. Unfortunately specific logic per filetype is out of scope for this library.

**Comment by seabre** [comment]
OK. Thanks!

**Pull request closed without merging**
