### PR TITLE
Updated to shared-mime-info 1.5

### PR DESCRIPTION
**Pull request by fedot**

### CODE REVIEW

**Comment by fedot** [comment]
For some reason running `rake tables` didn't work for me so I the desired command by hand:

`script/generate-mime.rb script/freedesktop.org.xml > lib/mimemagic/tables.rb`

**Comment by fedot** [comment]
I've closed/reopened to trigger a new build on Travis CI but ruby 1.9.3 builds are still fail (while I'm able to pass it locally with 1.9.3)

**Comment by RobCherry** [comment]
@fedot The 1.9.3 build issue is due to bundler on Travis CI.  I have a fix in #37.

**Comment by RobCherry** [comment]
Also, if 1.6 is available if you want to update your PR.

**Comment by fedot** [comment]
I've created a new pull-request (#38) for 1.6

**Pull request closed without merging**
