### PR TITLE
Mimetype extensions are now ordered by freedesktop.org's priority

### PR DESCRIPTION
**Pull request by epitron**
Hi again!

I didn't realize `table.rb` was autogenerated. I took a look at `freedesktop.org.xml`, and it turns out the file extensions are already ordered by popularity! This pull request removes the `sort` call from the generator, and then regenerates the table.

(I think it would still be nice to add a `default_extension` method.)

### CODE REVIEW

**Comment by minad** [comment]
Good. I will pull this soon.

**Comment by epitron** [comment]
Excellent!

**Comment by epitron** [comment]
*twiddles thumbs*

**Comment by epitron** [comment]
*tumbleweed*

**Comment by epitron** [comment]
*crickets*

**Comment by epitron** [comment]
bump.

**Comment by minad** [comment]
Merged.

**Comment by epitron** [comment]
Could you also to a release?

**Comment by minad** [comment]
Done

**Comment by epitron** [comment]
Yay!!! Thank you!

**Pull request closed without merging**
