### PR TITLE
Fix magic of Office Open XML types

### PR DESCRIPTION
**Pull request by ppostma**
This fixes issue #39.

### CODE REVIEW

**Comment by plicjo** [comment]
I'm looking at your tests. Shouldn't the assertion be that it should not equal `application/zip` with your changes?
You have it as equaling the `application/zip`. That's the current, undesired behavior.

Please let me know if I'm seeing this wrong.

**Comment by ppostma** [comment]
Thanks for commenting. I've double checked it:

The test I've added is for the case when the overlay magic is not used. It then detects the OO XML file as `application/zip`.

The test [here](https://github.com/minad/mimemagic/blob/master/test/mimemagic_test.rb#L60) loads the overlay magic and checks for the correct mime type for each file, which it does successfully.

**Comment by plicjo** [comment]
Oh ok, thanks for the double check! I appreciate that.

I'm seeing another issue. That test already passes without your changes.

Wouldn't you need to add another test that covers the situation when you have the overlay magic required and it fails to correctly identify a word/excel file without your code and passes with it?

I tested your code in my project locally against the issue in #39 with a Google Docs generated word file and it still recognized it as an `application/zip`.

**Comment by junaruga** [comment]
Hi @ppostma could you rebase on latest master branch when you have a time?

**Comment by junaruga** [comment]
Reference: Another PR to fix #39 
https://github.com/minad/mimemagic/pull/52

**Comment by atambo** [comment]
I fixed the merge conflicts for the other PR that fixes this issue here: https://github.com/minad/mimemagic/pull/64

**Pull request closed without merging**
