### PR TITLE
Change testing framework from bacon to minitest.

### PR DESCRIPTION
**Pull request by junaruga**
I changed the testing framework to `minitest`.
This fixes https://github.com/minad/mimemagic/issues/60 .

There is a issue.

Below test is randomly failed on my environment.

```
$ which ruby
/usr/local/ruby-2.5.1/bin/ruby

$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]

$ which bundle
/usr/local/ruby-2.5.1/bin/bundle

$ bundle -v
Bundler version 1.16.1

$ bundle install --path vendor/bundle

$ bundle list
Gems included by the bundle:
  * bundler (1.16.1)
  * mimemagic (0.3.2)
  * minitest (5.11.3)
  * rake (12.3.1)

$ bundle exec rake test
Run options: --seed 58090

# Running:

............F

Finished in 0.009302s, 1397.4866 runs/s, 7632.4267 assertions/s.

  1) Failure:
TestMimeMagic#test_recognize_xlsx_as_zip_without_magic [/home/jaruga/git/mimemagic/test/mimemagic_test.rb:56]:
--- expected
+++ actual
@@ -1 +1 @@
-#<MimeMagic:0xXXXXXX @type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", @mediatype="application", @subtype="vnd.openxmlformats-officedocument.spreadsheetml.sheet">
+"application/zip"


13 runs, 71 assertions, 1 failures, 0 errors, 0 skips
rake aborted!
Command failed with status (1)
/home/jaruga/git/mimemagic/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/local/ruby-2.5.1/bin/bundle:23:in `load'
/usr/local/ruby-2.5.1/bin/bundle:23:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)
```

But when running only the specified test case, it is always success.
```
$ bundle exec rake test TEST=test/mimemagic_test.rb TESTOPTS="--name=test_recognize_xlsx_as_zip_without_magic -v"
Run options: --name=test_recognize_xlsx_as_zip_without_magic -v --seed 22452

# Running:

TestMimeMagic#test_recognize_xlsx_as_zip_without_magic = 0.00 s = .

Finished in 0.002283s, 438.0704 runs/s, 876.1408 assertions/s.

1 runs, 2 assertions, 0 failures, 0 errors, 0 skips
```

Do you know the reason?
I think in `MimeMagic magic_match` method,  the result and the logic of `MAGIC.send(method) { |type, matches| magic_match_io(io, matches, buffer) }` might be something wrong.

I also moved the class `IOObject` and `StringableObject` to outside of the testing method.
Because we can not define inside of the method.

### CODE REVIEW

**Comment by junaruga** [comment]
Ah I might find the reason.

MimeMagic add/remove methods are editing the state of `TYPES`, `MAGIC` and etc..
We should use initialized MimeMagic for each test cases.

I will rebase my commit.

**Comment by junaruga** [comment]
@minad finally the tests are passed.
Review please.

- Maybe later we might be able to implement `MimeMagic.reset` method to reset the state of `EXTENSIONS`, `TYPES` and `MAGIC`.
- I changed `require "mimemagic/overlay"` to `load "mimemagic/overlay.rb"` to load it forcely every time.

**Comment by minad** [comment]
Looks good. Such a reset method might be a good idea, however mutating the internal state might just be a bad idea in general. Maybe using some kind of overlays would be a better idea. I think there already is something like an overlay for custom additions.

I am fine with this patch and it only touches the testing code, so lgtm :+1:

**Comment by junaruga** [comment]
Thanks for the merging. Your opinion about mutating the internal state makes sense for me :)

**Pull request merged**
