### PR TITLE
Handle Office Open XML types for filed generated outside MSOffice

### LINKED ISSUE #39: Doesn't detect XLSX when generated by OpenOffice/Googledocs
I just used this gem to detect files by content, and it works perfectly.

The only thing I detected is, that the Overlay features for xlsx, docx is only working for files generated by Microsoft Office. When they are exported by Google Docs or OpenOffice, they are not detected properly.

``` ruby
# Stunden.xlsx is exported from google docs
MimeMagic.by_magic(File.open('Stunden.xlsx'))                                                              
 => #<MimeMagic:0x00000003401ea8 @type="application/zip", @mediatype="application", @subtype="zip"> 

# ex03_Grade Report.xlsx saved by Microsoft Excel 
MimeMagic.by_magic(File.open('ex03_Grade Report.xlsx'))                                                      
 => #<MimeMagic:0x000000033ea230 @type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", @mediatype="application", @subtype="vnd.openxmlformats-officedocument.spreadsheetml.sheet">
```

### PR DESCRIPTION
**Pull request by atambo**
I rebased https://github.com/minad/mimemagic/pull/52 against master and fixed the merge conflicts.

This is the original description:

> It turns out that the position of '[Content_Types].xml' is not fixed in
this format, and whereas MS Office adds it in the beginning in general,
when files are generated using Google Docs, or RubyXL, this is not
necessarily true. They might add it at the end, so all these would be
detected as application/zip.

This fixes #39

### CODE REVIEW

**Comment by gsar** [comment]
@atambo this is not a good way to fix it.  please see: https://github.com/minad/mimemagic/pull/52#issuecomment-420375363

**Comment by atambo** [comment]
@gsar I modifed it to look for `[Content_Types].xml` within the offset range `0..5000`. That seems to work for the test cases @rosa had in the original PR. I'm not sure if that is a universal fix though, do you think maybe I should increase the offset range to be like an infinite range offset like `0..Float::INFINITY`?

**Comment by gsar** [comment]
Thanks @atambo. No, testing a bigger chunk of the file is a bad idea due to the performance and memory implications.

**Comment by atambo** [comment]
@minad do you think this PR could be merged/released?

**Comment by justisb** [comment]
Would definitely be great to get this fix live.

**Comment by rintaun** [comment]
@minad It would be great if this could be merged

**Pull request merged**
