### PR TITLE
Update: shared-mime-info to 2.0

### PR DESCRIPTION
**Pull request by benkoshy**
Thank you for your efforts in this library.

This solves the problem alluded to in:  #93, remedies the erroneous PR in #94, and also solves: #4,  #74, and also #49 in a more permanent way.

Please do review and let me know if there is something that can be fixed.

Ben

### CODE REVIEW

**Comment by BKSpurgeon** [comment]
@janko 
hi there Janko

If possible, is it possible to review and push to Ruby gems, because it attempts to fix a few bugs that are causing considerable consternation atm.

Am deeply grateful and thankful for the time you've put into open source.

rgds

Ben

**Comment by leviwilson** [comment]
Thanks, @benkoshy. We are also experiencing issues with #49 as well and found this PR that might work for us.

@janko any chance to look at this yet?

**Comment by benkoshy** [comment]
(To be fair to Janko, who's not the maintainer of this library: I did speak presumptuously in asking Janko to merge it - given Janko's stupendous contribution to Open Source and also incidentally to Janko having admin rights to this library. 

@leviwilson  What I've done is created a fork and my Gemfile points to that particular commit in that fork. such an approach might work for you, if you're having problems

**Comment by minad** [comment]
I updated the database to 2.1

**Comment by leviwilson** [comment]
@minad thanks; will there be a release soon?

**Comment by minad** [comment]
@leviwilson Please give it a test if the current master version works and then I can publish a new release.

**Comment by leviwilson** [comment]
@minad when I used @benkoshy 's branch, it was working for me.

In `master` I get this (we're using Rails / Paperclip)

```
/Users/levi.wilson/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/paperclip-6.1.0/lib/paperclip.rb:68:in `require': cannot load such file -- mimemagic/overlay (LoadError)
```

That's because https://github.com/thoughtbot/paperclip/blob/e3f7493b4cc954405a0209d26933830333ae2869/lib/paperclip.rb#L68 requires it here, but it's no longer in `master` because of the last commit.

**Comment by minad** [comment]
Okay, I will publish the new version as 1.0.0.

**Comment by leviwilson** [comment]
@minad thank you; I've tried this version and it does NOT fix #49 like the branch @benkoshy has.

@benkoshy did you do something special to get #49 working?

**Comment by minad** [comment]
@leviwilson You can check for differences of the table.rb generated from the shared-mime-info 2.0 with the version in master and the version generated by @benkoshy.

**Comment by leviwilson** [comment]
@minad I guess I'm misunderstanding why this PR was closed if it closes those issues that were mentioned?

**Comment by minad** [comment]
The PR was closed because I regenerated the table myself from an even newer version 2.1 instead of 2.0 as in this PR. In case you want to check, you can use a shared-mime-info package from https://www.freedesktop.org/wiki/Software/shared-mime-info/.

**Comment by benkoshy** [comment]
> @minad thank you; I've tried this version and it does NOT fix #49 like the branch @benkoshy has.
> 
> @benkoshy did you do something special to get #49 working?

From memory i just updated the database.  The upstream database had incorporated a PR which solved the problem.  Unless there's a reversion in 2.1?

**Comment by leviwilson** [comment]
@benkoshy there must be a reversion, but I'm having a difficult time spotting _what_ that would be.

All I know is:

* `master` doesn't work for #49 for me
* #95 _does_ resolve #49 for me

I pulled both locally (`master` and `git fetch origin pull/95/head:shared-mime-info-2.0`) and did a diff looking for `pdf` / `zip` but nothing popped out to my untrained eye to spot the differences.

**Comment by leviwilson** [comment]
@minad would there be issues with merging this MR (with the 2.0 update) independently of the 2.1 update and then also releasing that?

I'm not able to spot the difference why there would be a regression, but it would be nice to be able to choose this version for the PDF changes (that are being misidentified as ZIP in #49).

**Comment by minad** [comment]
This does not sound like a robust long-term solution to me. It is better to figure out the issue. Then I can make a new release.

**Comment by leviwilson** [comment]
@minad understood...and advices towards being able to do so?

I've done _some_ custom mime magic before in our application regarding office documents, but I'm not seeing the PDF problem (the difference between 2.0 and 2.1).

I'd share a file except the ones I have contain sensitive information. The one in this branch I can test to see, though, how it responds.

**Comment by minad** [comment]
I am also not sure what the issue is here. I suggest you debug the issue with the relevant files and look into which of the matchers detects the file.

**Comment by benkoshy** [comment]
@leviwilson hey Levi,

I've updated my local branch to the latest changes in upstream/master, and cannot reproduce the problems with zip files being incorrectly identified, given the test fixtures i added before. i cannot be sure of what is causing your particular problem at your end.

**Comment by leviwilson** [comment]
@benkoshy gotcha, thanks for the follow up. I'll keep digging then. In my case, it's a ZIP file _of_ PDFs.

**Pull request closed without merging**
