### PR TITLE
update to shared-mime-info-1.10

### PR DESCRIPTION
**Pull request by jrochkind**
Last update was to shared-mime-info-1.6 in June of 2016. f99d7233d632221

### CODE REVIEW

**Comment by jrochkind** [comment]
Also, 

Would you consider releasing a 1.0 version? I think it's ready. 

And I notice that the releases 0.3.1 and 0.3.2 don't seem to have tags in the repo. There is a tab `v0.3.0`, but that seems to be the last one. Tags in the repo make it a lot easier for anyone later to be sure they know exactly what changed by versions.  It would be awesome if that practice could be restored with future releases. (One way is to use the rake tasks that come with bundler for gem release, which automatically do git tags and pushes too. I can PR addition of those rake tasks if you are interested).

**Comment by peterwake** [comment]
Firstly - thanks for this gem - it is very useful for us.

I agree with @jrochkind that it would be great to bump the version and tag it again.

**Comment by jrochkind** [comment]
Hi, is this gem maintained?

**Comment by peterwake** [comment]
Thanks @minad 👍

**Comment by jrochkind** [comment]
@peterwake :  @minad closed the PR, but did not actually merge it. I'm not sure if that was a mistake, or means they are not interested in this PR to update the shared-mime-info db?

**Comment by minad** [comment]
I did the update by hand

**Comment by jrochkind** [comment]
OK thanks then!

**Pull request closed without merging**
