### PR TITLE
Travis: Use Bundler < 2

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR **fixes the build** by using an earlier Bundler.

### CODE REVIEW

**Comment by minad** [comment]
is there a better way to fix the issue?

**Comment by olleolleolle** [comment]
To upgrade (one-way) the Gemfile is another way to make the upgrade. 

The matrix may or may not support it.

**Comment by olleolleolle** [comment]
@minad Bundler 2:

https://bundler.io/blog/2019/01/03/announcing-bundler-2.html

The following is the full list of changes to Bundler 2:

- Removed support for Ruby < 2.3
- Removed support for RubyGems < 3.0.0

**Comment by olleolleolle** [comment]
Happy Monday <3

**Comment by minad** [comment]
Thanks for your help!

**Pull request merged**
