### PR TITLE
Handle Office Open XML types for filed generated outside MSOffice

### LINKED ISSUE #39: Doesn't detect XLSX when generated by OpenOffice/Googledocs
I just used this gem to detect files by content, and it works perfectly.

The only thing I detected is, that the Overlay features for xlsx, docx is only working for files generated by Microsoft Office. When they are exported by Google Docs or OpenOffice, they are not detected properly.

``` ruby
# Stunden.xlsx is exported from google docs
MimeMagic.by_magic(File.open('Stunden.xlsx'))                                                              
 => #<MimeMagic:0x00000003401ea8 @type="application/zip", @mediatype="application", @subtype="zip"> 

# ex03_Grade Report.xlsx saved by Microsoft Excel 
MimeMagic.by_magic(File.open('ex03_Grade Report.xlsx'))                                                      
 => #<MimeMagic:0x000000033ea230 @type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", @mediatype="application", @subtype="vnd.openxmlformats-officedocument.spreadsheetml.sheet">
```

### PR DESCRIPTION
**Pull request by rosa**
This is another stab to fix #39. We run into this same problem using `mimemagic`. 

It looks like the check for `[Content_Types.xml]` was added [in addition](https://github.com/minad/mimemagic/pull/26#issue-100928804) to the zip file check to avoid false positives using Paperclip. This keeps the zip check plus the `xl/` (and `word/` and `ppt/`) in the first 5000 bytes, without assuming that `'[Content_Types].xml'` will always be the first file in the archive.

This pull request also adds additional tests with a file generated by RubyXL (the one provided [in this comment](https://github.com/minad/mimemagic/issues/39#issuecomment-241944486)) and a file generated with Google Docs.

### CODE REVIEW

**Comment by atambo** [comment]
@minad / @junaruga is it possible for you to merge this or would you merge another PR if I take this and fix the merge conflicts?

**Comment by atambo** [comment]
@minad @junaruga I fixed the merge conflicts here: https://github.com/minad/mimemagic/pull/64

**Comment by junaruga** [comment]
@atambo thanks. @minad could you check this? Sorry I am still not familiar with this project.

**Comment by gsar** [comment]
@rosa I don't think this change is a good idea. Lots of zip files (eg. png) could have the 'xl/' characters accidentally in the first 5000bytes of the files, so there is a big risk of misidentifying such files.  I would suggest keeping the `[Content_types].xml` check but make it more relaxed about the position where it needs to be at.

**Comment by rosa** [comment]
@gsar 👍 Thanks for taking a look!
At the end we worked around this issue in a different way, so I'll close this PR and will open a new one if we run into this again (and if nobody makes the change you suggests first, of course!).

**Pull request closed without merging**
